version: '3.4'

services:
  mariadb:
    image: mariadb
    build:
      context: .
      dockerfile: sql/Dockerfile
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: admin

  memcached:
    image: memcached
    networks:
      - net
    ports:
      - "11211:11211"

  demo.exchange.api:
    image: demo/demo-exchange-api
    build:
      context: .
      dockerfile: src/Demo.Exchange.Api/Dockerfile
    networks:
      - net
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    depends_on:
      - memcached
      - mariadb

networks:
  net:
    driver: bridge
